# Generated by Django 5.2.7 on 2025-11-05 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais_origen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Calzado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('talla', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='calzados/')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calzados', to='calzados_api.marca')),
            ],
        ),
    ]
